### ISSUE TITLE
建议使用命名空间, 特别是User类, 很容易和现有系统的User类冲突

### ISSUE THREAD

**Issue by zhaishuaigan** [rongcloud/server-sdk-php#26]
建议使用命名空间, 特别是User类, 很容易和现有系统的User类冲突, 另外建议做成composer的扩展, 没有命名空间的类很容易和现在的系统冲突, 我都是手动给每个类加上了命名空间

**Comment by zsj1029** [comment]
自己加就好了，没问题的，加好默认会走composer 自动加载
