### ISSUE TITLE
在sdk中没有找到sendNotify发送通知类短信方法，但在官网中有提到

### ISSUE THREAD

**Issue by qiufeng5LIFE** [rongcloud/server-sdk-php#28]
![default](https://user-images.githubusercontent.com/24695287/30577896-a822d1c6-9d43-11e7-97df-5aae212c2257.png)
官网中提到的sendNotify发送通知类短信方法在sdk中并没有找到，请问发送通知类短信有什么替代的方法吗？

**Comment by shuise** [comment]
请按照 API 自行实现

**Comment by qiufeng5LIFE** [comment]
请问现在是否支持长短信？

**Comment by shuise** [comment]
http://www.rongcloud.cn/docs/sms_service.html#billing

**Comment by qiufeng5LIFE** [comment]
好的，已解决，谢谢。
在sdk SendRequest.php  curl方法中发送消息时curl_setopt($ch, CURLOPT_DNS_USE_GLOBAL_CACHE, false);这一行会报错，注释掉之后可以正常使用，请问是什么原因？

**Comment by shuise** [comment]
相关配置是否开启了呢？

**Comment by qiufeng5LIFE** [comment]
配置都开启了，注释之后是可以正常使用的，主要是我是通过composer安装的，每次部署之后都需要手动去sdk中注释掉这一行才可以使用。测试其他平台的短信服务也都是是正常的！
