### ISSUE TITLE
将sdk同步到Packagist

### ISSUE THREAD

**Issue by twn39** [rongcloud/server-sdk-php#8]
希望能够将sdk同步到Packagist

**Comment by changxiaoqiang** [comment]
您好，多谢提醒，马上就会同步上去

**Comment by changxiaoqiang** [comment]
您好，已提交 https://packagist.org/packages/rongcloud/php-sdk#dev-master 欢迎使用提供宝贵意见。对应 github 库：https://github.com/rongcloud/server-sdk-php-composer

**Comment by twn39** [comment]
:+1:

**Comment by xi4oh4o** [comment]
👍

**Comment by wdd2007** [comment]
新版本2.0没有同步过去。。。 Packagist 上还是1.0版本。

**Comment by kankaner** [comment]
@changxiaoqiang 你好Packagist什么时候能更新？Packagist1.0的能支持现在的安卓v2么

**Comment by joystrong** [comment]
希望composer更新到2.0
